language: node_js
cache:
  yarn: true
  directories:
    - .ng_pkg_build
notifications:
  email: false
node_js:
  - '10'

install:
  - yarn install
after_success:
  - npm run semantic-release
branches:
  only:
    - master