language: node_js
cache:
  yarn: true
  directories:
    - ~/.yarn
    - .ng_pkg_build
notifications:
  email: false
node_js:
  - '9'

install:
  - npm global add @angular/cli
  - yarn add  @angular/compiler
  - yarn global add @angular/compiler-cli
  - yarn global add ng-packagr
  - yarn global add tsickle
  - yarn global add typescript
  - yarn install

after_success:
  - npm run semantic-release
branches:
  only:
    - master