language: node_js
cache:
  directories:
    - ~/.yarn
    - .ng_pkg_build
notifications:
  email: false
node_js:
  - '9'

install:
  - yarn install -g @angular/cli
  - yarn install -g @angular/compiler
  - yarn install -g @angular/compiler-cli
  - yarn install -g ng-packagr
  - yarn install -g tsickle
  - yarn install -g typescript
  - yarn install

after_success:
  - npm run semantic-release
branches:
  only:
    - master